### PR TITLE
Clarify what files need to be included

### PR DESCRIPTION
**Pull request by cadop**
This PR clarifies for absolute beginners that the installation of a single file is only possible when using the base theme, and the sidebar only theme requires both files.

### CODE REVIEW

**Comment by Jhstvf4t** [comment]
I don't have money anymore to go out to the workshop, I want to eat, let alone me

**Comment by cadop** [comment]
uh, that was a weird comment.  But in any case, @jothepro , do you want to merge this?  I can delete the PR if you don't want to add the language.

**Comment by jothepro** [comment]
Also the account commented in multiple issues and discussions in this repo, always the same message, until I blocked the account. Weird.

I haven't forgotten about your MR, I'm just too involved in other things right now to apply your improvements. I plan to restructure the installation instructions a bit based on your feedback, so this will likely not be merged but definitely be an inspiration to fix the flaw in the documentation that you addressed. 😊

**Comment by cadop** [comment]
ha! okay

**Pull request closed without merging**
